export type ProductSurface = "paper" | "ink";

/** Visual-only token map. Paper matches the live landing; ink uses signed-in grounds. */
export const productSurface = {
  paper: {
    shell: "rounded-lg border border-rule bg-paper",
    panel: "rounded-sm border border-rule bg-paper p-4",
    header: "border-b border-rule px-4 py-3",
    well: "flex-1 bg-paper-raised p-4",
    hover: "transition-colors duration-150 hover:border-edge",
    title: "text-h3 text-ink",
    caption: "mt-1 text-body-sm text-ink-mid",
    eyebrow: "text-eyebrow text-ink-faint",
    badge: "rounded-sm border border-rule px-2 py-0.5 text-label text-ink-mid",
    label: "text-label text-ink-faint",
    mid: "text-body-sm text-ink-mid",
    sm: "text-body-sm text-ink",
    fg: "text-ink",
    body: "text-body font-medium text-ink",
    mono: "text-mono text-ink",
    monoMid: "text-mono text-ink-mid",
    faint: "text-mono text-ink-faint",
    row: "border-b border-rule",
    totalRule: "border-t border-ink",
    monoLg: "text-mono-lg text-ink",
    note: "text-body-sm text-ink-faint",
    ghostBtn:
      "inline-flex h-10 min-w-0 flex-1 cursor-default items-center justify-center rounded-sm border border-edge px-3 text-label text-ink",
    solidBtn:
      "inline-flex h-10 min-w-0 flex-1 cursor-default items-center justify-center rounded-sm bg-ink px-3 text-label text-paper",
    band: "bg-ink text-paper",
    bandMid: "text-ground-mid",
    ctaSecondary: "border-ground-edge text-paper hover:bg-surface",
  },
  ink: {
    shell: "rounded-lg border border-ground-rule bg-surface text-ground-ink",
    panel: "rounded-sm border border-ground-rule bg-surface p-4 text-ground-ink",
    header: "border-b border-ground-rule px-4 py-3",
    well: "flex-1 bg-surface-raised p-4",
    hover: "transition-colors duration-150 hover:border-ground-edge",
    title: "text-h3 text-ground-ink",
    caption: "mt-1 text-body-sm text-ground-mid",
    eyebrow: "text-eyebrow text-ground-faint",
    badge: "rounded-sm border border-ground-rule px-2 py-0.5 text-label text-ground-mid",
    label: "text-label text-ground-faint",
    mid: "text-body-sm text-ground-mid",
    sm: "text-body-sm text-ground-ink",
    fg: "text-ground-ink",
    body: "text-body font-medium text-ground-ink",
    mono: "text-mono text-ground-ink",
    monoMid: "text-mono text-ground-mid",
    faint: "text-mono text-ground-faint",
    row: "border-b border-ground-rule",
    totalRule: "border-t border-ground-ink",
    monoLg: "text-mono-lg text-ground-ink",
    note: "text-body-sm text-ground-faint",
    ghostBtn:
      "inline-flex h-10 min-w-0 flex-1 cursor-default items-center justify-center rounded-sm border border-ground-edge px-3 text-label text-ground-ink",
    solidBtn:
      "inline-flex h-10 min-w-0 flex-1 cursor-default items-center justify-center rounded-sm bg-ground-ink px-3 text-label text-ground",
    band: "bg-ground text-ground-ink",
    bandMid: "text-ground-mid",
    ctaSecondary: "border-ground-edge text-ground-ink hover:bg-surface-raised",
  },
} as const;
